/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

Formula : Aggregate of MEASURE / DIMENSION

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/



-- 1) Find the total number of customers by countries

SELECT 
country,
COUNT(customer_id) AS TOTAL_CUS
FROM
dim_customers
GROUP BY country
ORDER BY TOTAL_CUS DESC;

-- 2) Find the total customers by gender

SELECT 
gender,
COUNT(customer_id) AS TOTAL_CUS
FROM
dim_customers
GROUP BY gender
ORDER BY TOTAL_CUS DESC;

-- 3)Find the total products by category

SELECT 
category,
COUNT(product_id) AS TOTAL_PRO
FROM
dim_products
GROUP BY category
ORDER BY TOTAL_PRO DESC;

-- 4)What is the Average cost in each category

SELECT
category,
ROUND(AVG(cost),2) AS AVG_COST
FROM
dim_products
GROUP BY category
ORDER BY AVG_COST DESC;

-- 5) What is total revenue generated for each category

SELECT 
dm.category,
SUM(fc.sales_amount) AS TOTAL_REVENUE
FROM
fact_sales fc
LEFT JOIN dim_products dm
ON fc.product_key=dm.product_key
GROUP BY dm.category
ORDER BY TOTAL_REVENUE DESC;

-- 6)Find the total revenue that is generated by each customer

SELECT
ff.customer_key,
dc.first_name,
dc.last_name,
SUM(ff.sales_amount) AS TOTAL_REV_FOR_EACH_CUS
FROM 
fact_sales ff
LEFT JOIN dim_customers dc
ON ff.customer_key=dc.customer_key
GROUP BY ff.customer_key,dc.first_name,dc.last_name
ORDER BY TOTAL_REV_FOR_EACH_CUS DESC;

-- 7)What is the distribution of sold items across countires

SELECT
dc.country,
SUM(ff.quantity) AS TOTAL_ITEMS_SOLD
FROM 
fact_sales ff
LEFT JOIN dim_customers dc
ON ff.customer_key=dc.customer_key
GROUP BY dc.country
ORDER BY TOTAL_ITEMS_SOLD DESC;

